### ISSUE TITLE
Confirmation of Connection

### ISSUE THREAD

**Issue by Aetherinox** [acheong08/rev-obsidian-sync#24]
I have nginx and docker setup, with the container running fine. Went into Obsidian, enabled publish / sync, and signed in. Created a new vault, and the progress says that it's uploading files successfully.

However, the volume folders are empty, and I can't access anything via the website using 
```
https://vault.domain.com/published/Vaultname/Path/To/File.md
```

There a step I'm missing? I even executed the CURL command to create a new user, and I can't even find out where that data is stored, no config files found, no db files, etc.

The data / volume folder is also empty.
```
var/lib/docker/volumes/obsidian-sync_sync_data/_data
```

**Comment by acheong08** [comment]
I got no clue how the docker works. Usually the database is found in the CWD of the executable

**Comment by acheong08** [comment]
> I have nginx and docker setup, 

What's your nginx config? For myself, I use a dedicated publish domain name (see https://github.com/acheong08/obi-sync/wiki/Nginx-Configuration) where you don't need to do /published but instead just `/vaultname/path/to/doc.md`

**Comment by Aetherinox** [comment]
> > I have nginx and docker setup,
> 
> What's your nginx config? For myself, I use a dedicated publish domain name (see https://github.com/acheong08/obi-sync/wiki/Nginx-Configuration) where you don't need to do /published but instead just `/vaultname/path/to/doc.md`

I am actually using that same config, so I removed /published/ off the end of the URL to try and access my vault, and it just says
> 404 page not found

and I made sure the URL to call is proper. I went as far as to login to my server via SSH, and physically search for the files to see if they uploaded, and it cannot find them. So I'm not sure what the heck I'm doing wrong. I have the sync plugin you guys provide installed, I have it configured with my URL, made sure the sync / publish features for core plugins is enabled. And it says it's even uploading successfully.

However, in the Sync section, it says:
> Your vault is at 28.14MB out of 10.00 GB.

I have a feeling it's uploading to Obsidian's servers and not mine.

And then of course, when executing the CURL command, if I try to execute it more than once, I get:
```
{"error":"not sign up!"}
```

And when I sign up a new user for the first time, I get
```
{"email":"email@gmail.com","name":"Test"}
```

**Comment by Aetherinox** [comment]
Ok, so it is actually storing files. It was just in an odd location, not like my other docker containers are. It wants to store the vault files in a .db file located in:
```
/var/lib/docker/overlay2/ID#/
```

I've never seen that before, normally containers store to whatever the mounted volume is. Not sure if that's because of how the docker-compose file is, but it's definitely not taking the defined data folder into consideration. Not sure how to go about fixing that, because I'm using the compose file your repo provides:

```
version: '3.8'

services:
  obsidian_sync:
    image: ghcr.io/acheong08/obi-sync:v0.1.4@sha256:e2877d09c33201c7e69297a4614c4cafebd3d8f23a20707d4bb1c2a55dbd3111
    container_name: obsidian_sync
    ports:
      - 3000:3000
    environment:
      - DOMAIN_NAME=domain.com
      - ADDR_HTTP=0.0.0.0:3000
      - SIGNUP_KEY=testkey4422
    volumes:
      - sync_data:/data

volumes:
  sync_data:
```

Still can't seem to figure out why I can't view the pages. Tried with and without `/published/`, both IP and domain, and it just returns 404 page not found, if I removed `/published/` from the URL.

If I re-add published, I get `"Site not found"` in json.
