### ISSUE TITLE
docker support？

### ISSUE THREAD

**Issue by wangweitung** [acheong08/rev-obsidian-sync#4]
thanks for your work，are there any possibilities that publish a docker version？

**Comment by acheong08** [comment]
Unlikely to work on it myself until I get full feature parity with the official sync. Feel free to make a PR though.

**Comment by wangweitung** [comment]
> Unlikely to work on it myself until I get full feature parity with the official sync. Feel free to make a PR though.

thanks for your reply。 hope to see docker version soon

**Comment by rmonvfer** [comment]
Hello! I'd be glad to open a PR adding Docker support, is that OK @acheong08?

I've also noticed that this is probably going to require some refactoring in the DB layer (e.g: removing hardcoded credentials and using an ORM to make future updates easier)

**Comment by acheong08** [comment]
100%!

**Comment by acheong08** [comment]
> removing hardcoded credentials

Ah yes. I forgot about the example user. 

> using an ORM to make future updates easier

👍🏻. Not something I have much experience in. Help would be greatly appreciated.

**Comment by acheong08** [comment]
Closed by #8

**Comment by wangweitung** [comment]
> Closed by #8

I noticed that docker version was published. thanks for ur work (@panoti).

adding docker run command makes it much more easier to use：

like how to run the docker，setting the port and register an account.

**Comment by acheong08** [comment]
> using an ORM to make future updates easier
@rmonvfer

I'm working on refactoring to use [gorm](https://gorm.io/) on the [gorm branch](https://github.com/acheong08/rev-obsidian-sync/tree/gorm).

**Comment by panoti** [comment]
@acheong08 I want to bring sign up to API handler instead of cmd. What do you think?

**Comment by acheong08** [comment]
> register an account.

I think I'll create a dedicated API/embedded page for that to make it easier in the future

> like how to run the docker

I'll need to learn that as well. I don't have it installed

**Comment by acheong08** [comment]
> @acheong08 I want to bring sign up to API handler instead of cmd. What do you think?

Lmao I was just typing that

**Comment by rmonvfer** [comment]
Great news! I'm almost done adding docker. I've decided to leave the rest for another issue (such as the ORM integration, which is already in progress as stated by @acheong08's comment above). I'll open a PR soon!

**Comment by rmonvfer** [comment]
Is this done? I can work on a docker-compose file to make the development setup even easier.

**Comment by acheong08** [comment]
> Is this done?

ORM: #12

Docker: #8 and #9

**Comment by panoti** [comment]
@wangweitung this is my `docker-compose.yml` file

```
version: '3.8'

services:
  obsidian_sync:
    image: ghcr.io/acheong08/rev-obsidian-sync:main
    container_name: obsidian_sync
    ports:
      - 3000:3000
    environment:
      - DOMAIN_NAME=localhost:3000
      - ADDR_HTTP=0.0.0.0:3000
      - SIGNUP_KEY=signup_key_secret
    volumes:
      - sync_data:/data

volumes:
  sync_data:
```

Sign up user

```
curl --request POST \
  --url http://localhost:3000/user/signup \
  --header 'Content-Type: application/json' \
  --data '{
	"email": "test@gmail.com",
	"password": "password",
	"name": "Test",
	"signup_key": "signup_key_secret"
}'
```
